# Generated by Django 5.2.5 on 2025-08-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_spotfeedback_qr_code_spotfeedback_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonafide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=150)),
                ('start', models.DateTimeField(verbose_name='From-Date')),
                ('end', models.DateTimeField(null=True, verbose_name='To-Date')),
                ('proof', models.FileField(blank=True, upload_to='bonafide/proof')),
                ('certificate', models.FileField(blank=True, upload_to='bonafide/proof/certificate')),
                ('Astatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('Mstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('Hstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonafide_student', to='core.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
