# Generated by Django 5.2.5 on 2025-08-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_bonafide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafide',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='To-Date'),
        ),
    ]
