# Generated by Django 5.2.5 on 2025-09-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_attendance_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bus_no', models.CharField(max_length=20)),
                ('total_seat', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register_no', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('boarding_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.boardingpoint')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.busroute')),
            ],
        ),
        migrations.AddField(
            model_name='boardingpoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_points', to='core.busroute'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='core.busroute')),
            ],
        ),
    ]
