# Generated by Django 5.2.5 on 2025-09-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_boardingpoint_busroute_busapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('bus_no', models.CharField(max_length=20)),
                ('total_seat', models.PositiveIntegerField()),
                ('boarding_points', models.TextField(help_text='Comma-separated list of boarding points')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_number', models.CharField(max_length=20)),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_register_no', models.CharField(max_length=30)),
                ('applicant_mobile_number', models.CharField(max_length=15)),
                ('applicant_boarding_point', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
