# Generated by Django 5.2.5 on 2025-09-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_bus_and_boarding_changes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transportation',
        ),
    ]
